# Generated by Django 4.0.6 on 2022-08-01 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_frequency', models.IntegerField()),
                ('last_collection', models.DateTimeField()),
                ('bin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question2.bin')),
                ('operation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='question2.operation')),
            ],
        ),
    ]
