# Generated by Django 4.0.6 on 2022-07-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NavigationReport',
            new_name='NavigationRecord',
        ),
    ]
