# Generated by Django 4.0.6 on 2022-07-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question1', '0003_alter_navigationrecord_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
